test_that("make_blank_section_names_lookup_csv returns correct structure and is empty", {
  result <- make_blank_section_names_lookup_csv()
  expect_s3_class(result, "tbl_df")
  expect_equal(nrow(result), 0)
  expect_equal(names(result), c("transcript_section", "day", "time", "section", "preferred_name", "formal_name", "transcript_name", "student_id"))
  expect_type(result$transcript_section, "character")
  expect_type(result$day, "character")
  expect_type(result$time, "character")
  expect_type(result$section, "character")
  expect_type(result$preferred_name, "character")
  expect_type(result$formal_name, "character")
  expect_type(result$transcript_name, "character")
  expect_type(result$student_id, "character")
}) 