#' Section Names Lookup Dataset
#'
#' A dataset containing mappings between Zoom transcript names and preferred names
#' for students and instructors. This dataset is used by the name matching workflow
#' to handle variations in how names appear in Zoom transcripts.
#'
#' @format A data frame with 5 columns:
#' \describe{
#'   \item{transcript_name}{The name as it appears in the Zoom transcript}
#'   \item{preferred_name}{The preferred name for the person}
#'   \item{formal_name}{The formal name (e.g., "Dr. John Smith")}
#'   \item{participant_type}{Type of participant: "enrolled_student", "instructor", "guest", or "unknown"}
#'   \item{student_id}{Student ID if applicable, otherwise NA}
#' }
#'
#' @source Generated by the name matching workflow when unmatched names are detected
#'
#' @examples
#' \dontrun{
#' # Load the lookup data
#' lookup <- load_section_names_lookup()
#'
#' # View the structure
#' head(lookup)
#' }
#'
#' @keywords datasets
"section_names_lookup"
