#' Package Data Documentation
#'
#' @title Data Objects in zoomstudentengagement Package
#' @name package_data
#' @description This package does not include static datasets. Instead, it provides functions to process and analyze Zoom transcript data that users provide.
#'
#' @details
#' The zoomstudentengagement package is designed to work with user-provided data rather than including static datasets. This approach ensures privacy and allows the package to be used with any institutional data without concerns about data sharing or licensing.
#'
#' ## Data Sources
#'
#' Users provide their own data through the following functions:
#' - `load_zoom_transcript()` - Load Zoom transcript files
#' - `load_roster()` - Load student roster data
#' - `load_section_names_lookup()` - Load name matching lookup tables
#' - `load_cancelled_classes()` - Load cancelled class information
#'
#' ## Generated Data
#'
#' The package generates various data structures during analysis:
#' - **Section Names Lookup**: Created by `create_name_lookup()` and saved with `write_section_names_lookup()`
#' - **Analysis Results**: Generated by analysis functions like `analyze_transcripts()`
#' - **Metrics and Reports**: Created by functions like `write_metrics()` and `write_transcripts_summary()`
#'
#' ## Example Data Workflow
#'
#' ```r
#' # Load user-provided data
#' transcript <- load_zoom_transcript("my_transcript.vtt")
#' roster <- load_roster("student_roster.csv")
#'
#' # Generate analysis results
#' results <- analyze_transcripts(transcript, roster)
#'
#' # Export generated data
#' write_metrics(results, "engagement_metrics.csv")
#' ```
#'
#' @seealso
#' \code{\link{load_zoom_transcript}} for loading transcript data
#' \code{\link{load_roster}} for loading roster data
#' \code{\link{create_name_lookup}} for creating name matching data
#' \code{\link{write_metrics}} for exporting analysis results
#'
#' @examples
#' # This package works with user-provided data
#' # No static datasets are included
#'
#' # Example of typical workflow:
#' \dontrun{
#' # Load your own data
#' transcript <- load_zoom_transcript("path/to/transcript.vtt")
#' roster <- load_roster("path/to/roster.csv")
#'
#' # Analyze and generate results
#' results <- analyze_transcripts(transcript, roster)
#'
#' # Export generated data
#' write_metrics(results, "my_analysis_results.csv")
#' }
#'
#' @keywords internal
NULL
