#' Section Names Lookup Dataset
#'
#' A dataset containing mappings between Zoom transcript names and preferred names
#' for students and instructors. This dataset is used by the name matching workflow
#' to handle variations in how names appear in Zoom transcripts.
#'
#' @format A data frame with 9 columns:
#' \describe{
#'   \item{course_section}{Course and section identifier (e.g., "101.A")}
#'   \item{day}{Day of the week or date}
#'   \item{time}{Class time}
#'   \item{course}{Course number}
#'   \item{section}{Section identifier}
#'   \item{preferred_name}{Student's preferred name}
#'   \item{formal_name}{Student's formal/legal name}
#'   \item{transcript_name}{Name as it appears in Zoom transcripts}
#'   \item{student_id}{Student identification number}
#' }
#'
#' @source Generated by the name matching workflow when unmatched names are detected
#'
#' @examples
#' \dontrun{
#' # Load the lookup data
#' lookup <- load_section_names_lookup()
#'
#' # View the structure
#' head(lookup)
#' }
#'
#' @keywords datasets
"section_names_lookup"
